### ISSUE TITLE
`peer_lookup_in_networking` is not a complete mapping between PeerID and PublicAddress

### ISSUE THREAD

**Issue by lyulka** [parallelchain-io/pchain-network#3]
## Background

[Upon receiving a GossipSub message](https://github.com/parallelchain-io/pchain-network/blob/90367aa1cd08824197cdf8f7d1d34a9c80661ac4/src/engine.rs#L143), `pchain_network` wraps it in an [Envelope](https://github.com/parallelchain-io/pchain-network/blob/90367aa1cd08824197cdf8f7d1d34a9c80661ac4/src/messages.rs#L32) structure before passing it to applications through the message gate chain.

Besides containing the message, Envelopes have an [origin](https://github.com/parallelchain-io/pchain-network/blob/90367aa1cd08824197cdf8f7d1d34a9c80661ac4/src/messages.rs#L34) field, which hold the public address of the peer which published the message. 

However, a GossipSub message only contains the [PeerID](https://docs.rs/libp2p-gossipsub/latest/libp2p_gossipsub/struct.Message.html#structfield.source) of its source. 

To get the Public Address associated with a Peer ID, the engine task maintains a map from PeerID to Public Address called [`peer_lookup_in_networking`](https://github.com/parallelchain-io/pchain-network/blob/90367aa1cd08824197cdf8f7d1d34a9c80661ac4/src/engine.rs#L93).

This map is populated [upon receiving an Identify message](https://github.com/parallelchain-io/pchain-network/blob/90367aa1cd08824197cdf8f7d1d34a9c80661ac4/src/engine.rs#L176). This is possible because the peer info contained in an Identify message contains the peer's [Public Key](https://docs.rs/libp2p/latest/libp2p/identify/struct.Info.html#).

## Problem

Because `peer_lookup_in_networking` needs to be [consulted](https://github.com/parallelchain-io/pchain-network/blob/90367aa1cd08824197cdf8f7d1d34a9c80661ac4/src/engine.rs#L150) to create an Envelope, a GossipSub message that is not in the map is *not* forwarded to applications. This imposes the requirement that a peer *must* have received Identify messages from every peer in order for all GossipSub messages to be forwarded to applications. 

This requirement is not guaranteed. In particular, note that `pchain-network` uses Kademlia for peer routing--this means that a peer will only be directly connected to a subset of nodes at any given time.

## Proposed solution

The libp2p PeerIDs specification states that in the “identity multihash” conversion between public keys and PeerIDs, public keys less than 42 bytes are [not hashed](https://github.com/libp2p/specs/blob/master/peer-ids/peer-ids.md#peer-ids).

This suggests that a simple conversion can be made between PeerID and PublicAddress, and that the map is unnecessary.

Research needs to be done on what the identity multihash conversion is, so that we can decide how to reverse the conversion.

**Comment by lyulka** [comment]
Jonas, please investigate [Message](https://docs.rs/libp2p/latest/libp2p/gossipsub/struct.Message.html), [RawMessage](https://docs.rs/libp2p/latest/libp2p/gossipsub/struct.RawMessage.html) (which contains the public key of its source), and the identity conversion, and write a recommendation as to how we should resolve this issue.

**Comment by jong319** [comment]
Does the protocol intend to process all incoming messages, even from "non-connected" peers? 

The protocol currently uses `peer_lookup_in_networking` to allow only messages from peers that have been added to the mapping in the `IdentifyEvent` to be processed. 

If the intention is to process all incoming messages without checking for authenticated addresses, there are 2 solutions. 

Solution 1: Opt to implement using `RawMessage` instead of `Message` to get the public key of the source which can be wrapped into the `Envelope` Struct to be processed.
However, max transmit size of messages is defined in behaviour.rs to be 2MB multiply by a factor of 2 for safety. Using `RawMessage` would mean message data is not compressed and will need to ensure the full raw message can be transmitted safely. 

Solution 2: Protocol's public address is of the type [u8;32] and hence no hashing actually occurs but multihash format is still implemented. This means that peerId can be easily converted to Public key, and no mapping is required. Protocol can continue using `Message` but include a simple function to convert Peerid to public address to wrap into the Envelope Struct.

**Comment by lyulka** [comment]
@jong319 

> Does the protocol intend to process all incoming messages, even from "non-connected" peers?

>The protocol currently uses peer_lookup_in_networking to allow only messages from peers that have been added to the mapping in the IdentifyEvent to be processed.

We will need to add some kind of authentication mechanism in the future to prevent somebody from connecting a lot of peers into the network and broadcasting a lot of junk messages, however,`peer_lookup_in_networking` is not intended to be this mechanism. In fact, we don’t do any checks upon receiving an Identify message in deciding whether to add the sender to the `peer_lookup_in_networking` map.

Right now, we are using it only to convert PeerID to Public Address (to be sure, @AlvinHon please confirm).

> Solution 2: Protocol's public address is of the type [u8;32] and hence no hashing actually occurs but multihash format is still implemented. This means that peerId can be easily converted to Public key, and no mapping is required. Protocol can continue using Message but include a simple function to convert PeerId to public address to wrap into the Envelope Struct.

So, I get that your tentative conclusion is that solution 2 is preferred. How do we convert from PeerID to Public Address?

**Comment by jong319** [comment]
@lyulka 

> So, I get that your tentative conclusion is that solution 2 is preferred. How do we convert from PeerID to Public Address?

As mentioned in the [PeerId](https://github.com/libp2p/specs/blob/master/peer-ids/peer-ids.md#peer-ids) documentation, the protocol's public address bytes are less than 42 bytes, hence no hashing is performed but multihash format is still followed. 

The multihash format simply implements a padding which contains a code, size, and digest. The Public Key of the peer is contained in the digest, we can call the digest using the `Multihash::digest()` function, and decode it back to PublicKey type using the `PublicKey::try_decode_protobuf()` function. A subsequent conversion from PublicKey to the pchain PublicAddress type should suffice.

**Comment by lyulka** [comment]
@jong319 ok, things make sense so far. I wanted to find out what exactly is in the code and size prefixes and how many bytes these are and [this](https://github.com/multiformats/multihash#format) says that they’re both 1 byte long (they’re varint, but the code of identity is [0x00](https://github.com/multiformats/multicodec/blob/master/table.csv) and the size of the digest is under 127, so the [varint encoding](https://github.com/multiformats/unsigned-varint) is 1 byte each).

**Comment by jong319** [comment]
@lyulka 
After reading the Multihash source code, it looks like the conversion from Public Key bytes to Peer Id simply adds 2 bytes, [0, 36] as a prefix, which aligns with the code and size of 0 and 36. I have confirmed this with some tests of my own as shown below.

![image](https://github.com/parallelchain-io/pchain-network/assets/97576524/792320d7-6bc4-4750-ab38-6133fc5951e7)
![image](https://github.com/parallelchain-io/pchain-network/assets/97576524/2e6cad5c-0c05-44a4-9157-15f6ff1a8266)

I also found out that the function` PublicKey::try_decode_protobuf() `can be used directly on peer id bytes to convert back to Public Key as it is capable of removing the first 2 bytes on its own.

**Comment by lyulka** [comment]
@jong319 it's a bit weird that the second byte is 36. I would have expected 32 since it should be size of the digest.

**Comment by jong319** [comment]
Public Address bytes is 32, while Public Key bytes is 36. 

PeerId is built from a **public key**, hence the size is 36 instead. The protocol performs a conversion from Public Key to Public Address for use in GossipSub messaging.

**Comment by lyulka** [comment]
Hmm. I didn't know about this. What happens in converting Public Address to `libp2p::identity::PublicKey`? What's in the extra 4 bytes? How do we convert from PublicKey back to PublicAddress? (the latter being the type we actually need)

Also: 

>from Public Key to Public Address

You mean the other way around, right?

**Comment by jong319** [comment]
The protocol uses Libp2p's definition of [Public Key](https://docs.rs/libp2p-identity/0.2.0/libp2p_identity/struct.PublicKey.html) which actually has a header in front. 

The output of it is as shown below. The first output is of Public Key type, while the second output is in bytes and it is actually of the type [u8;36]. 
![image](https://github.com/parallelchain-io/pchain-network/assets/97576524/8620b62f-a999-4604-96e0-da7d9e96a64d)

For Public Address, the protocol has a function in network/conversions.rs to change Public Key type to Public Address type [u8;32]. This is the Public Address Bytes. 
![image](https://github.com/parallelchain-io/pchain-network/assets/97576524/45c776c1-646b-4369-a34f-cd8e492c1a2f)

I would assume the 4 extra bytes come from the header of the Public Key type, which defines the type of key it is, in this case: ed25519.

So the current process is as such: receive [Message](https://docs.rs/libp2p-gossipsub/latest/libp2p_gossipsub/struct.Message.html) from peer. Convert Peer Id (source) to Public Key type. Convert Public Key type to Public Address [u8;32]. Pass Public Address into Envelope Struct for further processing.

**Comment by lyulka** [comment]
>I would assume the 4 extra bytes come from the header of the Public Key type, which defines the type of key it is, in this case: ed25519.

Is there any official libp2p documentation, code comments, or other material that explains and/or specifies this?

**Comment by AlvinHon** [comment]
> In fact, we don’t do any checks upon receiving an Identify message in deciding whether to add the sender to the peer_lookup_in_networking map.
> > 
> Right now, we are using it only to convert PeerID to Public Address (to be sure, @AlvinHon please confirm).

Yes, it is true. The map is also used to make sure the node only proceed message from nodes which have gone through Identify protocol.

**Comment by jong319** [comment]
After much digging through the source code, i found out that the function `encode_protobuf()` is causing the extra 4 bytes. In the source [code](https://docs.rs/libp2p-identity/0.2.0/src/libp2p_identity/keypair.rs.html#471-500), the function calls a `write_message` function which adds 4 extra bytes. 
![image](https://github.com/parallelchain-io/pchain-network/assets/97576524/0e1fdcae-1f08-426b-85ce-d36e4ec1819e)
It explains where the first 4 bytes come from, [8, 1, 18, 32]. 

It does't affect any of the protocol's functions as it is only in constructing a Peer Id that this `encode_protobuf()` functions is called.

**Comment by lyulka** [comment]
>The map is also used to make sure the node only proceed message from nodes which have gone through Identify protocol.

Having read libp2p material quite thoroughly, I am confident that only processing messages from nodes that have sent an Identify message has no value (and is actually the cause of the problem that we are trying to solve, which is that some messages that we should process won't be processed).

In particular, Noise already guarantees that connections are *authenticated* and *secret*, while [by default](https://docs.rs/gossipsub/latest/gossipsub/enum.MessageAuthenticity.html) GossipSub already signs all messages, guaranteeing *non-repudiability*.

**Comment by lyulka** [comment]
> After much digging through the source code, i found out that the function `encode_protobuf()` is causing the extra 4 bytes. In the source [code](https://docs.rs/libp2p-identity/0.2.0/src/libp2p_identity/keypair.rs.html#471-500), the function calls a `write_message` function which adds 4 extra bytes. ![image](https://user-images.githubusercontent.com/97576524/257769212-0e1fdcae-1f08-426b-85ce-d36e4ec1819e.png) It explains where the first 4 bytes come from, [8, 1, 18, 32].
> 
> It does't affect any of the protocol's functions as it is only in constructing a Peer Id that this `encode_protobuf()` functions is called.

Ok. Then I guess it's just some protobuf thing that isn't worth looking into deeper.

**Comment by jong319** [comment]
@AlvinHon @lyulka 

The network handle returned by `engine::start()` uses `peer_lookup_in_networking` in its output `peer_lookup`. It is used in the network.rs function `list_addresses()`. Is this function vital to the protocol?

**Comment by lyulka** [comment]
>The network handle returned by engine::start() uses peer_lookup_in_networking in its output peer_lookup. It is used in the network.rs function list_addresses(). Is this function vital to the protocol?

Not only is being able to list "every address in the network" not required by the protocol, it is impossible.

The idea is that "the network" can have an arbitrarily large number of nodes, and each node will only be aware of, and connected to, a small subset of this (but with a topology that ensures that there is a reasonably-sized path between any pair of peers).

I do not require "list_addresses" to stay, but if it is being used somewhere in our codebase that I don't know and the functionality is still desired, then it can be achieved by simply returning what is in the peer's local routing table (k buckets).

Note that v0.4.3. should be non-breaking.

**Comment by lyulka** [comment]
Fixed in release v0.4.3.
