### ISSUE TITLE
`PutRecord` and `AddProvider` events are not filtered out

### ISSUE THREAD

**Issue by lyulka** [parallelchain-io/pchain-network#5]
## Background

Kademlia is not just a peer routing solution. It is a Distributed Hash Table.

Kademlia nodes store “records”, each identified by key. Additionally, libp2p Kademlia store special records called “Provider records” to support IPFS, which is the project from which libp2p was spun off from.

However `pchain_network`’s use case is purely to be a peer routing solution for GossipSub. In this use case, we *do not* require `pchain_network` nodes to store *any* records.

## Problem

Records can be added to a Kademlia cluster using [put_record](https://docs.rs/libp2p/latest/libp2p/kad/struct.Kademlia.html#method.put_record), and Provider Records can be added using [start_providing](https://docs.rs/libp2p/latest/libp2p/kad/struct.Kademlia.html#method.start_providing).

Malicious Kademlia cluster participants can use these methods to put many big records onto Kademlia nodes, causing memory and storage exhaustion. 

Kademlia nodes can protect against this by setting up a “Record Filter”. However, [by default, this filter is not configured](https://docs.rs/libp2p/latest/libp2p/kad/struct.KademliaConfig.html#method.set_record_filtering).

## Proposed Solution

A future, non-breaking update to `pchain-network` should override the default and set a Record Filter that filters out *all* `PutRecord` and `AddProvider` [requests](https://docs.rs/libp2p/latest/libp2p/kad/enum.InboundRequest.html#).

Research must be done to identify further ways malicious nodes can spam honest nodes with junk records.

**Comment by lyulka** [comment]
@jong319, please read [set_record_filtering](https://docs.rs/libp2p/latest/libp2p/kad/struct.KademliaConfig.html#method.set_record_filtering) and other background material.

Tell me if my assessment of the problem is correct, and if setting record filtering to [FilterBoth](https://docs.rs/libp2p/latest/libp2p/kad/enum.KademliaStoreInserts.html#variant.FilterBoth) will resolve the issue.

**Comment by jong319** [comment]
I've been looking at the source code the past few days, and record_filtering is used in the functions `record_received` and `provider_received`. These are handled by the `KademliaHandlerEvent` which checks for the `PutRecord` and `AddProvider` events, which are repeatedly queried even if there are no records to be stored. 

By default, record_filtering is set to **Unfiltered**. When receiving the `PutRecord` and `AddProvider` events, it calls the `put_record` and `add_provider` functions, storing the records. 

By setting it to **FilterBoth**, it skips calling those functions and simply push the event to the back of the queue to be queried again later. 

However, the `start_providing` function does not consider record_filtering, and it still publishes a provider record. However, this function seems to be a local operation and not something that can be initiated by other nodes. It is mainly used in establishing the local node as a provider. 

So yes, setting it to FilterBoth will prevent most records from being stored. 

Currently, I am working on testing the difference between setting it as FilterBoth and Unfiltered. Mainly to see the impact of removing records from the network.

**Comment by lyulka** [comment]
Fixed in release v0.4.3.
